
POSTGRE_HOST = '127.0.0.1'
POSTGRE_PORT = '5432'
POSTGRE_USER = 'user_id'
POSTGRE_PASSWORD = 'password'
POSTGRE_DATABASE = 'aiohttp'
POSTGRE_DSN = f'postgres://{POSTGRE_USER}:{POSTGRE_PASSWORD}@{POSTGRE_HOST}:{POSTGRE_PORT}/{POSTGRE_DATABASE}'

